name: Deploy to Azure Web App

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Set your preferred Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # For Python, change based on your app

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
    - name: Clean up Git configuration
    run: |
    git config --global --unset http.https://github.com/.extraheader
    git config --global --unset credential.helper 
      
      with:
        app-name: infocmain  # Replace with your Azure Web App name
        slot-name: 'production'  # Use 'staging' if deploying to a staging slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
